version: '3.8'

services:
  api:
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --log-level debug

  worker:
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - PYTHONPATH=/app
      - DEBUG=1
    command: celery -A app.worker.celery_app worker --loglevel=debug --pool=solo --autoreload

  flower:
    environment:
      - DEBUG=1
    command: celery -A app.worker.celery_app flower --port=5555 --broker=redis://redis:6379/0 --debug 