version: '3.8'

services:
  api:
    environment:
      - DEBUG=1
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    environment:
      - DEBUG=1
      - LOG_LEVEL=debug
      - ENVIRONMENT=development
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: celery -A app.worker.celery_app worker --loglevel=debug --pool=solo --concurrency=1

  flower:
    environment:
      - ENVIRONMENT=development
    volumes:
      - .:/app 